SolicitudEmpleados.MVCV3/Controllers/TiposPropiedadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolicitudEmpleado.Helpers;
using SolicitudEmpleado.Data;
using SolicitudEmpleado.Models;

namespace SolicitudEmpleados.MVCV3.Controllers
{
    public class TiposPropiedadsController : BaseController
    {
        private dbSolicitudesContext db = new dbSolicitudesContext();

        // GET: TiposPropiedads
        public ActionResult Index(int id = 0, int id1 = 0, int id2 = 0)
        {
            ViewBag.ListaPropiedades = new SelectList(db.Propiedades.OrderBy(p=>p.Nombre), "PropiedadID", "Nombre");
            ViewBag.ListaTipos = new SelectList(db.Tipos.Where(p => p.Activo).OrderBy(p => p.Nombre), "TipoID", "Nombre");
            ViewBag.ListaPropiedadTipos = new SelectList(db.PropiedadTipoes.OrderBy(p => p.Nombre), "TipoPropiedadID", "Nombre");

            var modelo = new ListadoTiposPropiedadesViewModel();
            modelo.Listado = db.TiposPropiedades.Include(t => t.Propiedade).Include(t => t.Tipos);

            if (id > 0)
            {
                modelo.Listado = modelo.Listado.Where(p => p.PropiedadID == id).ToList();
                modelo.PropiedadId = id;
            }
            if (id1 > 0)
            {
                modelo.Listado = modelo.Listado.Where(p => p.TipoID == id1).ToList();
                modelo.TipoId = id1;
            }
            if (id2 > 0)
            {
                modelo.Listado = modelo.Listado.Where(p => p.Propiedade.TipoPropiedadID == id2).ToList();
                modelo.PropiedadTipoId = id2;
            }

            return View(modelo);
        }

        // GET: TiposPropiedads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposPropiedad tiposPropiedad = db.TiposPropiedades.Find(id);
            if (tiposPropiedad == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
                    return PartialView(tiposPropiedad);

            return View(tiposPropiedad);
        }

        // GET: TiposPropiedads/Create
        public ActionResult Create(int id = 0, int id1 = 0, int id2 = 0)
        {
            if (id2 > 0)
            {
                ViewBag.PropiedadID = new SelectList(db.Propiedades.Where(p=>p.TipoPropiedadID == id2), "PropiedadID", "Nombre");
            }
            else
            {
                ViewBag.PropiedadID = new SelectList(db.Propiedades.OrderBy(p => p.Nombre), "PropiedadID", "Nombre");
            }

            ViewBag.TipoID = new SelectList(db.Tipos.Where(p => p.Activo), "TipoID", "Nombre", id1);

            if (Request.IsAjaxRequest())
                    return PartialView();

            return View();
        }

        // POST: TiposPropiedads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TiposPropiedadesID,TipoID,PropiedadID,Requerido,Guardar,GuardarHistorial,Orden")] TiposPropiedad tiposPropiedad)
        {
            if (ModelState.IsValid)
            {
                if (tiposPropiedad.Orden == null)
                {
                    tiposPropiedad.Orden = 0;
                }

                db.TiposPropiedades.Add(tiposPropiedad);

                try
                {
                    db.SaveChanges();
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    ViewBag.PropiedadID = new SelectList(db.Propiedades.OrderBy(p => p.Nombre), "PropiedadID", "Nombre", tiposPropiedad.PropiedadID);
                    ViewBag.TipoID = new SelectList(db.Tipos.Where(p => p.Activo), "TipoID", "Nombre", tiposPropiedad.TipoID);

                    ModelState.AddModelError("", "No se ha podido Guardar Tipo Propiedad. Por los siguientes errores: ");
                    var listaValidaciones = ((System.Data.Entity.Validation.DbEntityValidationException)ex).EntityValidationErrors;
                    foreach (var item in listaValidaciones)
                    {
                        foreach (var itemInside in item.ValidationErrors)
                        {
                            ModelState.AddModelError("", " Error " + itemInside.PropertyName + " " + itemInside.ErrorMessage + ".");
                        }
                    }

                    return View(tiposPropiedad);
                }
                catch (Exception ex)
                {

                    ViewBag.PropiedadID = new SelectList(db.Propiedades.OrderBy(p => p.Nombre), "PropiedadID", "Nombre", tiposPropiedad.PropiedadID);
                    ViewBag.TipoID = new SelectList(db.Tipos.Where(p => p.Activo), "TipoID", "Nombre", tiposPropiedad.TipoID);

                    ModelState.AddModelError("", "No se ha podido Guardar Tipo Propiedad. Por los siguientes errores: ");
                    ModelState.AddModelError("", ex.Message);

                    if (ex.InnerException != null)
                    {
                        string mensajeErrorInner = ex.InnerException.ToString();
                        if (mensajeErrorInner.Length > 500)
                        {
                            mensajeErrorInner = mensajeErrorInner.Substring(0, 500);
                        }
                        ModelState.AddModelError("", mensajeErrorInner);
                    }

                    return View(tiposPropiedad);
                }

                TempData["MensajeError"] = "ok|Se Ha Actualizado Correctamente.";
                return RedirectToAction("Index", new { id1 = tiposPropiedad.TipoID, id2 = db.Propiedades.Find(tiposPropiedad.PropiedadID).TipoPropiedadID });
            }

            return RedirectToAction("Index", new { id1 = tiposPropiedad.TipoID, id2 = db.Propiedades.Find(tiposPropiedad.PropiedadID).TipoPropiedadID });
        }

        // GET: TiposPropiedads/Edit/5
        public ActionResult Edit(int? id, int id1 = 0, int id2 = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposPropiedad tiposPropiedad = db.TiposPropiedades.Find(id);
            if (tiposPropiedad == null)
            {
                return HttpNotFound();
            }

            if (id2 > 0)
            {
                ViewBag.PropiedadID = new SelectList(db.Propiedades.Where(p => p.TipoPropiedadID == id2).OrderBy(p => p.Nombre), "PropiedadID", "Nombre", tiposPropiedad.PropiedadID);
            }
            else
            {
                ViewBag.PropiedadID = new SelectList(db.Propiedades.OrderBy(p => p.Nombre), "PropiedadID", "Nombre", tiposPropiedad.PropiedadID);
            }

            ViewBag.TipoID = new SelectList(db.Tipos.Where(p => p.Activo), "TipoID", "Nombre", tiposPropiedad.TipoID);

            if (Request.IsAjaxRequest())
                return PartialView(tiposPropiedad);

            return View(tiposPropiedad);
        }

        // POST: TiposPropiedads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TiposPropiedadesID,TipoID,PropiedadID,Requerido,Guardar,GuardarHistorial,Orden")] TiposPropiedad tiposPropiedad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tiposPropiedad).State = EntityState.Modified;
                db.SaveChanges();
                TempData["MensajeError"] = "ok|Se Ha Actualizado Correctamente.";
                return RedirectToAction("Index", new { id1 = tiposPropiedad.TipoID, id2 = db.Propiedades.Find(tiposPropiedad.PropiedadID).TipoPropiedadID });

            }

            ViewBag.PropiedadID = new SelectList(db.Propiedades.OrderBy(p=>p.Nombre), "PropiedadID", "Nombre", tiposPropiedad.PropiedadID);
            ViewBag.TipoID = new SelectList(db.Tipos, "TipoID", "Nombre", tiposPropiedad.TipoID);

            return RedirectToAction("Index", new { id1 = tiposPropiedad.TipoID, id2 = db.Propiedades.Find(tiposPropiedad.PropiedadID).TipoPropiedadID });

        }

        // GET: TiposPropiedads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposPropiedad tiposPropiedad = db.TiposPropiedades.Find(id);
            if (tiposPropiedad == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
                return PartialView(tiposPropiedad);

            return View(tiposPropiedad);
        }

        // POST: TiposPropiedads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TiposPropiedad tiposPropiedad = db.TiposPropiedades.Find(id);
            db.TiposPropiedades.Remove(tiposPropiedad);
            db.SaveChanges();
            TempData["MensajeError"] = "ok|Se Ha Eliminado Correctamente.";

            //if (Request.IsAjaxRequest())
            //    return PartialView();


SolicitudEmpleados.MVCV3/Views/TiposPropiedads/Create.cshtml
@model SolicitudEmpleado.Data.TiposPropiedad

@{
    ViewBag.Title = "Nuevo Tipos Propiedad";
}

<div class="row">
    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TipoID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TipoID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PropiedadID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PropiedadID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropiedadID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Requerido, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.Requerido)
                            @Html.ValidationMessageFor(model => model.Requerido, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Guardar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.Guardar)
                            @Html.ValidationMessageFor(model => model.Guardar, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GuardarHistorial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.GuardarHistorial)
                            @Html.ValidationMessageFor(model => model.GuardarHistorial, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EsUnico, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.EsUnico)
                            @Html.ValidationMessageFor(model => model.EsUnico, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Orden, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Orden, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Orden, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>

@if (Request.IsAjaxRequest())
{
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
}
else
{
    @section scripts {
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    }
}

SolicitudEmpleados.MVCV3/Views/TiposPropiedads/Delete.cshtml
@model SolicitudEmpleado.Data.TiposPropiedad

@{
    ViewBag.Title = "Eliminar Tipos Propiedad";
}

<div class="row">
    <div class="col-md-12">

        <h3 class="titulo">@ViewBag.Title</h3>

        <h5>Esta seguro que desea eliminar este registro?</h5> @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

        <dl class="dl-horizontal">
            <dt>
                @Html.LabelFor(model => model.Propiedade, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Propiedade.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Tipos, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tipos.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Requerido, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Requerido)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Guardar, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Guardar)
            </dd>

            <dt>
                @Html.LabelFor(model => model.GuardarHistorial, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GuardarHistorial)
            </dd>

            <dt>
                @Html.LabelFor(model => model.EsUnico, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EsUnico)
            </dd>
            <dt>
                @Html.LabelFor(model => model.Orden, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Orden)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions">
                <input type="submit" value="Eliminar" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

SolicitudEmpleados.MVCV3/Views/TiposPropiedads/Details.cshtml
@model SolicitudEmpleado.Data.TiposPropiedad

@{
    ViewBag.Title = "Detalles Tipos Propiedad";
}

<div class="row">

    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>


        <dl class="dl-horizontal">
            <dt>
                @Html.LabelFor(model => model.Propiedade, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Propiedade.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Tipos, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tipos.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Requerido, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Requerido)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Guardar, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Guardar)
            </dd>

            <dt>
                @Html.LabelFor(model => model.GuardarHistorial, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GuardarHistorial)
            </dd>

            <dt>
                @Html.LabelFor(model => model.EsUnico, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EsUnico)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Orden, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Orden)
            </dd>

        </dl>
    </div>

</div>

SolicitudEmpleados.MVCV3/Views/TiposPropiedads/Edit.cshtml
@model SolicitudEmpleado.Data.TiposPropiedad

@{
    ViewBag.Title = "Editar Tipos Propiedad";
}

<div class="row">
    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.TiposPropiedadesID)
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TipoID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TipoID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PropiedadID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PropiedadID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropiedadID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Requerido, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.Requerido)
                            @Html.ValidationMessageFor(model => model.Requerido, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Guardar, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.Guardar)
                            @Html.ValidationMessageFor(model => model.Guardar, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GuardarHistorial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.GuardarHistorial)
                            @Html.ValidationMessageFor(model => model.GuardarHistorial, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EsUnico, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="">
                            @Html.EditorFor(model => model.EsUnico)
                            @Html.ValidationMessageFor(model => model.EsUnico, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Orden, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Orden, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Orden, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Guardar" class="btn btn-primary" />

                </div>
            </div>
        }
    </div>
</div>

@if (Request.IsAjaxRequest())
{
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
}
else
{
    @section scripts {
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    }
}

SolicitudEmpleados.MVCV3/Views/TiposPropiedads/Index.cshtml
@model SolicitudEmpleado.Models.ListadoTiposPropiedadesViewModel

@{
    ViewBag.Title = "Tipos Propiedades";
}
<div class="row">
    <div class="col-md-12">

        <h3 class="titulo">@ViewBag.Title</h3>
        @Html.Partial("_MensajeError")
        <div class="row">

            <div class="col-md-3" style="z-index: 1;">

                @Html.DropDownListFor(model => model.TipoId, ViewBag.ListaTipos as SelectList , new { @class = "form-control"})

            </div>

            <div class="col-md-3" style="z-index: 1;">

                @Html.DropDownListFor(model => model.PropiedadTipoId, ViewBag.ListaPropiedadTipos as SelectList , new { @class = "form-control"})

            </div>

            <div class="col-md-3" style="z-index: 1;">

                @Html.DropDownListFor(model => model.PropiedadId, ViewBag.ListaPropiedades as SelectList , new { @class = "form-control"})

            </div>

        </div>
        <table class="display table table-bordered table-hover">
            <thead>
                <tr>

                    <th>
                        Solicitud Tipo
                    </th>
                    <th>
                        Propiedad Tipo
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Propiedade.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Requerido)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Guardar)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().EsUnico)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Orden)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Listado)
            {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Tipos.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Propiedade.PropiedadTipo.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Propiedade.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Requerido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Guardar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EsUnico)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Orden)
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                            Accion
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#" onclick="cargarModal('@Url.Action("Details", "TiposPropiedads", new { id=item.TiposPropiedadesID })')">Detalle</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#" onclick="cargarModal('@Url.Action("Edit", "TiposPropiedads", new { id=item.TiposPropiedadesID, id1 = Model.TipoId, id2 = Model.PropiedadTipoId})')">Editar</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#" onclick="cargarModal('@Url.Action("Delete", "TiposPropiedads", new { id=item.TiposPropiedadesID })')">Eliminar</a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
            }
            </tbody>
        </table>

        <div class="form-actions">
            <a href="#" class="btn btn-primary" onclick="cargarModal('@Url.Action("Create", "Propiedades", new { id = Model.PropiedadTipoId, solicitudTipoId = Model.TipoId })')">Crear Nueva Propiedad</a>
            <a href="#" class="btn btn-primary" onclick="cargarModal('@Url.Action("Create", "TiposPropiedads", new { id1 = Model.TipoId, id2 = Model.PropiedadTipoId })')">Crear Nuevo Tipo Propiedad</a>
        </div>
    </div>
</div>

@section scripts{

    @*Datatable BEING*@
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.jqueryui.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
    @*Datatable END*@

    <!-- Mi Codigo Data Table -->
    <script src="~/Scripts/myCodeDataTable.js"></script>

    <script>

        $(document).ready(function () {

            var nombreDelBoton = "#PropiedadId";
            $(nombreDelBoton).change(function () {
                var selectedValue = $(nombreDelBoton).val();
                var div = document.getElementById(nombreDelBoton.replace('#', ''));
                var divRoot = document.getElementsByTagName("body")[0].getAttribute('data-root');
                var url = divRoot + 'TiposPropiedads/Index/' + selectedValue;
                Redirect(url);

            });

            var nombreDelBoton1 = "#TipoId";
            $(nombreDelBoton1).change(function () {
                var selectedValue = $(nombreDelBoton1).val();
                var div = document.getElementById(nombreDelBoton1.replace('#', ''));
                var divRoot = document.getElementsByTagName("body")[0].getAttribute('data-root');
                var url = divRoot + 'TiposPropiedads/Index/?id1=' + selectedValue + '&id2=' +  $(nombreDelBoton2).val();
                Redirect(url);
        
            });

            var nombreDelBoton2 = "#PropiedadTipoId";
            $(nombreDelBoton2).change(function () {
                var selectedValue = $(nombreDelBoton2).val();
                var div = document.getElementById(nombreDelBoton2.replace('#', ''));
                var divRoot = document.getElementsByTagName("body")[0].getAttribute('data-root');
                var url = divRoot + 'TiposPropiedads/Index/?id1=' + $(nombreDelBoton1).val() + '&id2=' + selectedValue;
                Redirect(url);
            
            });

        });

    </script>
}