SolicitudEmpleado.MVC/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolicitudEmpleado.Data;
using SolicitudEmpleado.DAL;
using SeguridadComun;
using Webdiyer.WebControls.Mvc;
using SolicitudEmpleado.Models;


namespace SolicitudEmpleado.MVC.Controllers
{
    public class ComentariosController : BaseController
    {

        #region Agregar Listado de Comentarios

        public PartialViewResult _Comentarios(int SolicitudID)
        {
            ViewBag.SolicitudID = SolicitudID;
            IEnumerable<Historial> historiales = unitOfWork.SolicitudesRepository.Get().Where(m => m.SolicitudID == SolicitudID).FirstOrDefault().Historials;
            return PartialView("_Comentarios", historiales);
        }

        [ChildActionOnly]
        public PartialViewResult _AgregarComentario(int SolicitudID)
        {
            var obj = new ComentarioViewModel();
            ViewBag.SolicitudID = obj.intSolicitudID;
            obj.intSolicitudID = SolicitudID;

            return PartialView("_AgregarComentario", obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult _ComentarioInsert(ComentarioViewModel obj)
        {
            ViewBag.SolicitudID = obj.intSolicitudID;
            Historial nuevoHistorial = new Historial()
            {
                SolicitudID = obj.intSolicitudID,
                FechaCreacion = DateTime.Now,
                CreadoPor = currentUser.codigoEmpleado,
                CreadoPorUsuarioDeRed = currentUser.usuario,
                Comentario = obj.strValor,
                EstatusID = 10
            };

            unitOfWork.HistorialRepository.Insert(nuevoHistorial);
            unitOfWork.Save();

            var db = new dbGrupoReserva();
            IEnumerable<Historial> historiales = db.Historials.Where(p => p.SolicitudID == obj.intSolicitudID).ToList();

            return PartialView("_Comentarios", historiales);
        }

        #endregion

    }
}

SolicitudEmpleado.MVC/Controllers/HistorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SolicitudEmpleado.MVC.Controllers
{
    public class HistorialController : BaseController
    {
        // GET: Historial
        public ActionResult Detalle(int id)
        {
            var coleccion = unitOfWork.HistorialRepository.Get().Where(p => p.HistorialID == id).FirstOrDefault();

            if (Request.IsAjaxRequest())
                return PartialView(coleccion);

            return View(coleccion);
        }
    }
}

SolicitudEmpleado.MVC/Views/Comentarios/_AgregarComentario.cshtml
@model SolicitudEmpleado.Models.ComentarioViewModel

@Html.HiddenFor(m => m.intSolicitudID)

<dl>
    <dt>
        Comentario:
    </dt>
    <dd>
        @Html.EditorFor(m => m.strValor)
    </dd>
    <dt>
        <button type="submit" class="btn"> Agregar Comentario </button>
    </dt>
</dl>

SolicitudEmpleado.MVC/Views/Comentarios/_Comentarios.cshtml
@model IEnumerable<SolicitudEmpleado.Data.Historial>

<div id="divComentarios">
    @if (Model.Count() > 0)
    {
        <h5>
            Datos De Historial
        </h5>
        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th>
                        Evento
                    </th>
                    <th>
                        Usuario
                    </th>
                    <th>
                        Fecha
                    </th>
                    <th>
                        Comentario
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (SolicitudEmpleado.Data.Historial value in Model)
                {
                    <tr>
                        <td>
                            <a href="#" onclick="cargarModal('@Url.Action("Detalle", "Historial", new { id = value.HistorialID })')">
                                @value.Estatu.Nombre
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => value.CreadoPorUsuarioDeRed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => value.FechaCreacion)
                        </td>
                        <td>
                            @if (String.IsNullOrEmpty(value.Comentario))
                            {
                                <span>N/A</span>
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => value.Comentario)
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    @using (Ajax.BeginForm("_ComentarioInsert", "Comentarios", new AjaxOptions() { UpdateTargetId = "divComentarios" }))
    {
        @Html.AntiForgeryToken()
        @Html.Action("_AgregarComentario", "Comentarios", new { SolicitudID = ViewBag.SolicitudID })
    }

</div>




