SolicitudEmpleado.MVC/Controllers/DisponibilidadController.cs
using SeguridadComun;
using SolicitudEmpleado.Data;
using SolicitudEmpleado.Helpers;
using SolicitudEmpleado.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SolicitudEmpleado.MVC.Controllers
{
    public class DisponibilidadController : BaseController
    {

        #region Paginas Actions

        public ActionResult Index()
        {
            ViewBag.EmpresaID = new SelectList(getListaEmpresa(), "EmpresaID", "Nombre");
            return View();
        }

        public ActionResult Detalle(int id, int empresa = 1)
        {
            var retVal = new DetalleDisponibViewModel();
			var empleado = BuscarUsuario(id);
			//var empleado = ws.BuscarEmpleadoUnico(id, empresa);

			retVal.codigoEmpleado = empleado.codigoEmpleado;
            retVal.nombreEmpleado = empleado.nombreCompleto;
			retVal.cedula = empleado.cedulaForm;
			retVal.posicion = empleado.puesto;
			retVal.tiempoServicio = "";
			retVal.fechaIngreso = DateTime.Now;
			retVal.Identificacion = empleado.cedulaForm;
            retVal.TipoIdentificacionID = 1;

            //Para Buscar Directamente en el Web Service.
            var objDisponbilidad = unitOfWork.SolicitudesRepository.GetDisponiblidadLista(id, empresa, true);

            //Para Buscar Como sale en procesar, agrupando los resultados.
            //var objDisponbilidad = unitOfWork.SolicitudesRepository.GetDisponiblidadLista(id, empresa, 0);

            retVal.ingresos = objDisponbilidad.Where(p => p.TipoPropiedadID == PropiedadesTipos.EditarIngresos).ToList();
            retVal.deduccio = objDisponbilidad.Where(p => p.TipoPropiedadID == PropiedadesTipos.EditarDeducciones).ToList();

            retVal.totalIngresos = objDisponbilidad.Where(p => p.TipoPropiedadID == PropiedadesTipos.TotalesIngresos).ToList();
            retVal.totalDeduccio = objDisponbilidad.Where(p => p.TipoPropiedadID == PropiedadesTipos.TotalesDeducciones).ToList();

            return View(retVal);
        }

        #endregion

        #region Lista Empleados JSON

        [HttpPost]
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public JsonResult EmpleadosList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = "", string codigoEmpleado = "", int EmpresaID = 1)
        {
            try
            {
                if (EmpresaID == 0)
                {
                    EmpresaID = 1;
                }
				//var listaEmpleados = ws.BuscarEmpleados(codigoEmpleado, EmpresaID, 1);
				var listaEmpleados = new List<Usuario>();

				var usuario = BuscarUsuario(int.Parse(codigoEmpleado));

				listaEmpleados.Add(usuario);

				return Json(new { Result = "OK", Records = listaEmpleados, TotalRecordCount = listaEmpleados.Count() });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        #endregion

    }
}

SolicitudEmpleado.MVC/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SeguridadComun;
using SolicitudEmpleado.Data;
using SolicitudEmpleado.DAL;
using SolicitudEmpleado.Helpers;
using SolicitudEmpleado.Models;
using SolicitudEmpleado.MVC.Componentes.Email;

namespace SolicitudEmpleado.MVC.Controllers
{
    /// <summary>
    /// Esta es la clase principal de todo el programa.
    /// </summary>
    public class SolicitudesController : BaseController
    {
        #region Procesar Resultados de Consultas a Solicitudes

        private List<int> listaEstado = new List<int>();

        private List<int> listaTipos = new List<int>();

        private IEnumerable<object> getResultado(int jtStartIndex, int jtPageSize, string jtSorting, string searchString, ref int intCantidad, int? empresaID = 0, int? estatusID = 0, int? tipoID = 0, int viewType = 0, int asignadoID = 0, string q = "", int qt = 0)
        {
            var solicitudes = (
                from obj in unitOfWork.SolicitudesRepository.Get(includeProperties: "TiposSolicitud")
                select new
                {
                    SolicitudID = obj.SolicitudID,
                    EmpresaID = obj.EmpresaID,
                    TipoSolicitudID = obj.TipoSolicitudID,
                    TipoID = obj.TipoID,
                    EstatusID = obj.EstatusID,
                    FechaSolicitud = obj.FechaSolicitud,
                    CodigoEmpleado = obj.CodigoEmpleado,
                    NombreEmpleado = obj.NombreEmpleado,
                    Direccion = obj.Direccion,
                    TelefonoOficina = obj.TelefonoOficina,
                    Extension = obj.Extension,
                    TelefonoCelular = obj.TelefonoCelular,
                    Email = obj.Email,
                    Posicion = obj.Posicion,
                    Departamento = obj.Departamento,
                    TiempoServicio = obj.TiempoServicio,
                    Cuenta = obj.Cuenta,
                    Sueldo = obj.Sueldo,
                    CreadoPor = obj.CreadoPor,
                    FechaCreacion = obj.FechaCreacion,
                    ModificadoPor = obj.ModificadoPor,
                    FechaModificacion = obj.FechaModificacion,
                    AsignadoA = obj.AsignadoA,
                    NumeroSolicitud = obj.NumeroSolicitud,
                    UsuarioDeRed = obj.UsuarioDeRed,
                    Cedula = obj.Identificacion,
                    AsignadoANombre = obj.AsignadoANombre,
                    Fecha = obj.FechaSolicitud,
                    EmpresaNombre = obj.Empresa.Nombre,
                    Monto = obj.Monto
                });

            if (!String.IsNullOrEmpty(searchString))
            {
                solicitudes = solicitudes.Where(p => p.CodigoEmpleado.ToString().ToUpper().Trim() == searchString.ToUpper() ||
                                                p.Cedula.ToUpper().ToUpper().Trim() == searchString.ToUpper() ||
                                                p.SolicitudID.ToString().ToUpper() == searchString.ToUpper() ||
                                                p.NombreEmpleado.Contains(searchString.ToUpper()));
            } 
     
            if (!String.IsNullOrEmpty(q))
            {
                if (qt == 0)
                {
                    solicitudes = solicitudes.Where(p => p.CodigoEmpleado.ToString() == q);
                }
                if (qt == 1)
                {
                    solicitudes = solicitudes.Where(p => p.Cedula == q);
                }
                if (qt == 2)
                {
                    solicitudes = solicitudes.Where(p => p.SolicitudID.ToString() == q);
                }
                if (qt == 3)
                {
                    solicitudes = solicitudes.Where(p => p.NumeroSolicitud == q);
                }

            }

            if ((estatusID == 0 || estatusID == null) && listaEstado.Count > 0)
            {
                if (viewType == stViewType.Pendientes && (tipoID == null || tipoID == 0) && (empresaID == null || empresaID == 0) && (asignadoID == 0))
                {
                    solicitudes = from p in solicitudes
                                    where p.EstatusID == 1
                                    select p;
                }
                else
                {
                    solicitudes = from p in solicitudes
                                    where listaEstado.Contains(p.EstatusID)
                                    select p;
                }

            }

            if (estatusID > 0)
            {
                solicitudes = from p in solicitudes
                                where p.EstatusID == estatusID
                                select p;

            }

            if ((tipoID == 0 || tipoID == null) && listaTipos.Count > 0)
            {
                solicitudes = from p in solicitudes
                                where listaTipos.Contains(p.TipoID)
                                select p;
            }

            if (tipoID > 0)
            {
                solicitudes = from p in solicitudes
                                where p.TipoID == tipoID
                                select p;
            }
            if (empresaID > 0)
            {
                solicitudes = from p in solicitudes
                                where p.EmpresaID == empresaID
                                select p;
            }
            if (asignadoID > 0)
            {
                solicitudes = solicitudes.Where(p => p.AsignadoA == asignadoID);
            }
      
            if (viewType == stViewType.MisSolicitudes)
            {
                solicitudes = solicitudes.Where(p => p.AsignadoA == currentUser.codigoEmpleado);
            }
          
            if (viewType == stViewType.Pendientes || viewType == stViewType.EnProceso)
            {
                if (viewType == stViewType.Pendientes && asignadoID <= 0)
                {
                    solicitudes = solicitudes.Where(p => p.AsignadoA == null || p.AsignadoA == 0);
                }
            }
            intCantidad = solicitudes.Count();
            return solicitudes.OrderBy(s => s.SolicitudID).Skip(jtStartIndex).Take(jtPageSize).ToList();
        }

        #endregion

        #region Llenar los Combo Box y Opciones de Resultados

        [HttpPost]
        public JsonResult GetEstatusOptions()
        {
            try
            {
                var estatus = getListaEstatus().Select(
                    c => new { DisplayText = c.Nombre, Value = c.EstatusID });
                return Json(new { Result = "OK", Options = estatus });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetTiposOptions()
        {
            try
            {
                var tipos = getListaTipo().Select(
                    c => new { DisplayText = c.Nombre, Value = c.TipoID });
                return Json(new { Result = "OK", Options = tipos });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetAsignadoOptions(int id = 0)
        {
            try
            {
                var tipos = getListaAsignado(0, id).Select(
                    c => new { DisplayText = c.AsignadoANombre, Value = c.AsignadoA });
                return Json(new { Result = "OK", Options = tipos });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        private void SetCombox(bool getEstadoEstatus = false)
        {
            int idModuloConsumo = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["Seguridad.PrestamosConsumo"]);
            var moduloConsumo = BuscarModulo(idModuloConsumo);

            int idModuloHipotecario = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["Seguridad.PrestamosHipotecarios"]);
            var moduloHipotecario = BuscarModulo(idModuloHipotecario);
            
            bool esSupervisor = (moduloConsumo.permisoEspecial || moduloHipotecario.permisoEspecial);

            listaEstado = unitOfWork.SolicitudesRepository.GetEstadosDropDown(esSupervisor).ToList();
           
            listaTipos = new List<int>();

            if (moduloConsumo.permisoLeer)
            {
                listaTipos.AddRange(unitOfWork.SolicitudesRepository.GetTiposPrestamos((int)ListaAccesos.ModuloConsumoLeer));
            }
            if (moduloHipotecario.permisoLeer)
            {
                listaTipos.AddRange(unitOfWork.SolicitudesRepository.GetTiposPrestamos((int)ListaAccesos.ModuloHipotecarioLeer));
            }
            if (moduloConsumo.permisoEspecial || moduloHipotecario.permisoEspecial)
            {
                ViewBag.Supervisor = "true";
            }

            if (!getEstadoEstatus)
            {
                ViewBag.EmpresaID = new SelectList(getListaEmpresa(), "EmpresaID", "Nombre");
                ViewBag.Asignado = new SelectList(getListaAsignado(), "AsignadoA", "AsignadoANombre");
                ViewBag.EstatusID = new SelectList(getListaEstatus(listaEstado.ToArray()), "EstatusID", "Nombre");
                ViewBag.TipoID = new SelectList(getListaTipo(listaTipos.ToArray()), "TipoID", "Nombre");
            }
        }

        #endregion


SolicitudEmpleado.MVC/Views/Disponibilidad/Detalle.cshtml
@model SolicitudEmpleado.Models.DetalleDisponibViewModel
@using SolicitudEmpleado.Helpers

@{
    ViewBag.Title = "Disponiblidad de los Últimos Períodos";
}

<div class="row">

    <h3 class="titulo">@ViewBag.Title</h3>

    <div class="row-fluid" style="
            margin-top: -10px;
            width: 85%;
            margin-left: auto;
            margin-right: auto; color: #777;">

        @Html.HiddenFor(p => p.Identificacion)
        @Html.HiddenFor(p => p.TipoIdentificacionID)

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.codigoEmpleado)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.codigoEmpleado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.nombreEmpleado)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.nombreEmpleado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cedula)
            </dt>
            <dd>
                @Intranet.Helpers.ClientesHelper.DarFormatoIdentificacion(Model.cedula)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.posicion)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.posicion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.tiempoServicio)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.tiempoServicio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fechaIngreso)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.fechaIngreso)
            </dd>
        </dl>


        <div id="divContenedorPrestamos"
             data-url="@Url.Action("","Solicitudes")">
        </div>

        <div class="row-fluid" style="width: 85%; margin-left: auto; margin-right: auto; color: #777; clear:both;">
            <div class="span6">
                <dl class="dl-horizontal">

                    <dt style="color: black;">
                        INGRESOS
                    </dt>
                    <dd>
                        &nbsp;
                    </dd>
                    @for (int i = 0; i < Model.ingresos.Count; i++)
                    {
                        <dt>
                            @Intranet.Helpers.CadenaHelper.ToTitleCase(Model.ingresos[i].Nombre)
                        </dt>
                        <dd>
                            @Html.DisplayForPropiedad(Model.ingresos[i].Valor, Model.ingresos[i].Tipo)
                        </dd>
                    }

                </dl>
            </div>
            <div class="span6">
                <dl class="dl-horizontal">

                    <dt style="color: black;">
                        DEDUCCIONES
                    </dt>
                    <dd>
                        &nbsp;
                    </dd>
                    @for (int i = 0; i < Model.deduccio.Count; i++)
                    {
                        <dt>
                            @Intranet.Helpers.CadenaHelper.ToTitleCase(Model.deduccio[i].Nombre)
                        </dt>
                        <dd>
                            @Html.DisplayForPropiedad(Model.deduccio[i].Valor, Model.deduccio[i].Tipo)
                        </dd>
                    }
                </dl>
            </div>
        </div>

        <div class="row-fluid" style="width: 85%; margin-left: auto; margin-right: auto; color: #777; clear:both;">
            <div class="span6">
                <dl class="dl-horizontal">

                    <dt style="color: black;">
                        TOTAL INGRESOS
                    </dt>
                    <dd>
                        &nbsp;
                    </dd>
                    @for (int i = 0; i < Model.totalIngresos.Count; i++)
                    {
                        <dt>
                            @Html.DisplayFor(model => model.totalIngresos[i].Nombre)
                        </dt>
                        <dd>
                            @Html.DisplayForPropiedad(Model.totalIngresos[i].Valor, Model.totalIngresos[i].Tipo)
                        </dd>
                    }

                </dl>
            </div>
            <div class="span6">
                <dl class="dl-horizontal">

                    <dt style="color: black;">
                        TOTAL DEDUCCIONES
                    </dt>
                    <dd>
                        &nbsp;
                    </dd>
                    @for (int i = 0; i < Model.totalDeduccio.Count; i++)
                    {
                        <dt>
                            @Html.DisplayFor(model => model.totalDeduccio[i].Nombre)
                        </dt>
                        <dd>
                            @Html.DisplayForPropiedad(Model.totalDeduccio[i].Valor, Model.totalDeduccio[i].Tipo)
                        </dd>
                    }
                </dl>
            </div>
        </div>

    </div>
</div>

@section scripts{

    @{
        //Para Usar un Tema de JQuery UI
        var jQueryStyle = "custom-theme/jquery-ui-1.10.3.custom.css";
        if (!string.IsNullOrEmpty(Request["jQueryStyle"]))
        {
            jQueryStyle = Request["jQueryStyle"];
        }

        var jTableStyle = "jqueryui/jtable_jqueryui.css";
        if (!string.IsNullOrEmpty(Request["jTableStyle"]))
        {
            jTableStyle = Request["jTableStyle"];
        }

    }

    <!-- JTable Control BEGIN -->
    <link href="@Url.Content("~/Content/themes/" + jQueryStyle)" rel="stylesheet" type="text/css" /> @*//Para Usar un Tema de JQuery UI*@
    <link href="@Url.Content("~/Scripts/jtable/themes/" + jTableStyle)" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/jquery.jtable.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/localization/jquery.jtable.es.js")"></script>
    <!-- JTable Control END -->

    <script src="~/Scripts/number_format.js"></script>
    <script src="~/Scripts/Disponibilidad/Detalle.js"></script>

}

SolicitudEmpleado.MVC/Views/Disponibilidad/Index.cshtml

@{
    ViewBag.Title = "Consulta Disponiblidad";
}

<div class="row">

    <h3 class="titulo">@ViewBag.Title</h3>

    <div style="height: 85px;">
        <form>

            <div class="column column-3">
                <label class="title">Código o Cédula</label>
                <div class="col-md-10">
                    <input type="text" name="codigoEmpleado" id="codigoEmpleado" />
                </div>
            </div>

            <div class="column column-3">
                <label class="title">Empresa</label>
                <div class="col-md-10">
                    @Html.DropDownList("EmpresaID", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <button type="submit" class="btn" id="btnBuscar" style="float: right;margin-top: 25px;width:50px;">
                <i class="icon-search"></i>
            </button>
            
        </form>

    </div>

    <div id="divContenedorDisponiblidad"
         data-url="@Url.Action("", "Disponibilidad")" >
    </div>

</div>

@section scripts{

    @{
       
        var jQueryStyle = "custom-theme/jquery-ui-1.10.3.custom.css";
        if (!string.IsNullOrEmpty(Request["jQueryStyle"]))
        {
            jQueryStyle = Request["jQueryStyle"];
        }

        var jTableStyle = "jqueryui/jtable_jqueryui.css";
        if (!string.IsNullOrEmpty(Request["jTableStyle"]))
        {
            jTableStyle = Request["jTableStyle"];
        }

    }

    <!-- JTable Control BEGIN -->
    <link href="@Url.Content("~/Content/themes/" + jQueryStyle)" rel="stylesheet" type="text/css" /> @*//Para Usar un Tema de JQuery UI*@
    <link href="@Url.Content("~/Scripts/jtable/themes/" + jTableStyle)" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/jquery.jtable.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/localization/jquery.jtable.es.js")"></script>
    <!-- JTable Control END -->
    <!-- Mi Codigo -->
    <script src="~/Scripts/number_format.js"></script>
    <script src="~/Scripts/Disponibilidad/Index.js"></script>

}